# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Audit

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup mise
      uses: jdx/mise-action@v2

    - name: Lint Scripts
      run: make lint
